import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import 'react-toastify/dist/ReactToastify.css';
import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css'; // Import CSS
import Header from '@/app/Layouts/Header';
import Footer from '@/app/Layouts/Footer';
import Sidebar from '@/app/Layouts/SideBar';
import { ToastContainer } from 'react-toastify';
import { decodeJWT } from './utils/decodeJwt';
import React from 'react';
import { cookies } from 'next/headers';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import SnowWrapper from './Layouts/SnowWrapper';

const queryClient = new QueryClient();
config.autoAddCss = false; // Tắt CSS tự động để tránh xung đột

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies(); 
  const token = cookieStore.get('token')?.value; 
  const decode = decodeJWT(token);
  
  
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ToastContainer
          position="bottom-right"
          autoClose={3000}
          style={{ zIndex: 9999 }}
        />
       
        <Header />
        {decode?.role === 'admin' ? <Sidebar>{children}</Sidebar> : <SnowWrapper>{children}</SnowWrapper>}

        <Footer />
      </body>
    </html>
  );
}
